name: random

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main
  workflow_dispatch:

jobs:
  Tests:
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest ] #, macos-latest ]
        python: [ 3.8, 3.8, 3.8, 3.8 ]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python }}
    - name: cache
      id: cache
      uses: actions/cache@v3
      with:
        path: data
        key: cache-${{ github.run_id }}
        restore-keys: cache-
    - name: Setup
      run: |
        python3 -m venv .env
        source .env/bin/activate
        python -m pip install -U pip setuptools
        python -m pip install numpy
        python -m pip install torch --extra-index-url https://download.pytorch.org/whl/cpu
    - name: Test random
      run: |
        source .env/bin/activate
        mkdir -p data
        python main.py
